[algokit]
min_version = "v1.12.1"

[generate.smart_contract]
description = "Adds new smart contract to existing project"
path = ".algokit/generators/create_contract"

[project]
type = 'contract'
name = 'py-dm-beginner-en'
artifacts = 'smart_contracts/artifacts'

[project.deploy]
command = "poetry run python -m smart_contracts deploy"
environment_secrets = [
  "DEPLOYER_MNEMONIC",
  "DISPENSER_MNEMONIC",
]

[project.deploy.localnet]
environment_secrets = []

[project.run]
# Commands intented for use locally and in CI
build = { commands = [
  'poetry run python -m smart_contracts build',
], description = 'Build all smart contracts in the project' }
test = { commands = [
  'poetry run pytest',
], description = 'Run smart contract tests' }
audit = { commands = [
  'poetry export --without=dev -o requirements.txt',
  'poetry run pip-audit -r requirements.txt',
], description = 'Audit with pip-audit' }
lint = { commands = [
  'poetry run black --check .',
  'poetry run ruff .',
  'poetry run mypy',
], description = 'Perform linting' }
lint-fix = { commands = [
  'poetry run black .',
  'poetry run ruff . --fix',
], description = 'Perform linting fix' }
audit-teal = { commands = [
  # ðŸš¨ IMPORTANT ðŸš¨: For strict TEAL validation, remove --exclude statements. The default starter contract is not for production. Ensure thorough testing and adherence to best practices in smart contract development. This is not a replacement for a professional audit.
  'algokit task analyze smart_contracts/artifacts --recursive --force --exclude rekey-to --exclude is-updatable --exclude missing-fee-check --exclude is-deletable --exclude can-close-asset --exclude can-close-account --exclude unprotected-deletable --exclude unprotected-updatable',
], description = 'Audit TEAL files' }

# Commands intented for CI only, prefixed with `ci-` by convention
ci-teal-diff = { commands = [
  'git add -N ./smart_contracts/artifacts',
  'git diff --exit-code --minimal ./smart_contracts/artifacts',
], description = 'Check TEAL files for differences' }
